name: VanillaExtra
main: com.github.sqyyy.vanillaextras.VanillaExtras
version: 0.1.0
api-version: '1.20'
author: sqyyy

commands:
  extras:
    usage: /<command> <key>
    permission: vanilla_extras.command